services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api
      - mongo-express
    restart: unless-stopped

  api:
    build: ./api
    expose:
      - "8080"
    depends_on:
      - mongo
      - gate-controller
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: unless-stopped

  ai:
    build: ./ai
    depends_on:
      - api
      - mongo
    environment:
      - API_URL=http://api:8080
      - USE_WEBCAM=false
      - CAM_ENTER_URL=rtsp://admin:123456@109.164.15.139:6002/h264
      - CAM_EXIT_URL=rtsp://admin:123456@109.164.15.139:6001/h264
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ai:/app
    restart: unless-stopped
    # Add extra hosts for better DNS resolution if needed
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gate-controller:
    build: ./gate-controller
    expose:
      - "3001"
    volumes:
      - ./gate-controller:/app
    privileged: true
    devices:
      - "/dev/gpiomem4:/dev/gpiomem4"
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiomem27:/dev/gpiomem27"
      - "/dev/gpiochip27:/dev/gpiochip27"
    restart: unless-stopped
    tty: true
    stdin_open: true

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./backups:/backup
      - ./mongo-init/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    restart: unless-stopped

  mongo-backup:
    image: mongo:6
    depends_on:
      - mongo
    volumes:
      - mongo-data:/data/db
      - ./mongo-backup/backup.sh:/backup.sh
      - ./backups:/backup
    entrypoint: /bin/bash
    command: -c "while true; do /backup.sh; sleep 3600; done"
    restart: unless-stopped

volumes:
  mongo-data:
