version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
      - ./backups:/backup
      - ./mongo-init/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    restart: unless-stopped

  mongo-backup:
    image: mongo:6
    depends_on:
      - mongo
    volumes:
      - mongo-data:/data/db
      - ./mongo-backup/backup.sh:/backup.sh
      - ./backups:/backup
    entrypoint: /bin/bash
    command: -c "while true; do /backup.sh; sleep 3600; done"
    restart: unless-stopped

  ai:
    build: ./ai
    volumes:
      - ./ai:/app
    ports:
      - "${AI_PORT}:${AI_PORT}"
    env_file:
      - .env
    environment:
      - AI_PORT=${AI_PORT}
      - MODEL_CONFIG_PATH=${MODEL_CONFIG_PATH}
      - MODEL_WEIGHTS_PATH=${MODEL_WEIGHTS_PATH}
      - CAMERA=${CAMERA}
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data:
